version: "3.2"

services:
  addresses-api:
    image: addresses-api
    build:
      context: AddressesAPI/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=devdb;Username=postgres;Password=mypassword
      - ELASTICSEARCH_DOMAIN_URL=http://localhost:9200
    links:
      - dev-database
      - dev-elasticsearch
  dev-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: dev-elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata-dev:/usr/share/elasticsearch/data
  dev-database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=devdb
    image: postgres:16
    container_name: dev-database
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres/seed-dev-data.sql:/var/seed-dev-data.sql

  addresses-api-test:
    image: addresses-api-test
    build:
      context: .
      dockerfile: AddressesAPI.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - ELASTICSEARCH_DOMAIN_URL= http://test-elasticsearch:9200
    links:
      - test-database
      - test-elasticsearch
    networks:
      - elastic
      - postgres
  test-database:
    image: postgres:16
    container_name: test-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=testdb
    networks:
      - postgres
  test-elasticsearch:
    image: test-elasticsearch
    container_name: test-elasticsearch
    build:
      context: .
      dockerfile: data/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9202:9200
    volumes:
      - esdata-test:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
          - test-elasticsearch
          - elastic
volumes:
  esdata-test:
    driver: local
  esdata-dev:
    driver: local
networks:
  elastic:
    driver: bridge
  postgres:
    driver: bridge
