version: "3.2"

services:
  addresses-api:
    image: addresses-api
    build:
      context: AddressesAPI/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - CONNECTION_STRING=Host=dev-database;Port=5432;Database=testdb;Username=postgres;Password=mypassword
    links:
      - dev-database
  dev-database:
    env_file:
      - database.env
    image: postgres:12
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  addresses-api-test:
    image: addresses-api-test
    build:
      context: .
      dockerfile: AddressesAPI.Tests/Dockerfile
    environment:
      - LLPGConnectionString="Data Source=test-database:6666;Initial Catalog=StubAdd;Integrated Security=False;User ID=sa;Password=Rooty-Tooty"
    links:
      - test-database
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: databaseTSQL/Dockerfile
    ports:
      - 6666:1433
    env_file:
      - database.env
