version: 2.1

orbs:
  node: circleci/node@7.2.1
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.1

executors:
  docker-python:
    docker:
      - image: cimg/python:3.7
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:light"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws

  terraform-init:
    description: "Initializes Terraform configuration for a specific environment"
    parameters:
      environment:
        type: string
    steps:
      - run:
          name: get and init
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init

  # terraform-preview:
  #   description: "Previews terraform configuration changes"
  #   parameters:
  #     environment:
  #       type: string
  #   steps:
  #     - *attach_workspace
  #     - checkout
  #     - terraform-init:
  #         environment: <<parameters.environment>>
  #     - run:
  #         name: preview
  #         command: |
  #           cd ./terraform/<<parameters.environment>>/
  #           terraform plan

  terraform-apply-changes:
    description: "Initializes and applies terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - terraform-init:
          environment: <<parameters.environment>>
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve

  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - node/install
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            sls deploy --stage <<parameters.stage>> --conceal

jobs:
  # TODO: replace the legacy linter with 'dotnet format'
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check
  # replace the docker-compose with 'docker compose' (space)
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build addresses-api-test
      - run:
          name: Run tests
          command: |
            docker-compose up -d test-elasticsearch
            docker-compose run addresses-api-test
  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION

  preview-terraform:
    executor: docker-terraform
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - terraform-init:
          environment: <<parameters.environment>>
      - run:
          name: Terraform Plan (Preview)
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan

  # preview-staging-terraform:
  #   executor: docker-terraform
  #   steps:
  #     - terraform-preview:
  #         environment: "staging"
  # preview-production-terraform:
  #   executor: docker-terraform
  #   steps:
  #     - terraform-preview:
  #         environment: "production"

  release-staging-terraform:
    executor: docker-terraform
    steps:
      - terraform-apply-changes:
          environment: "staging"
  release-production-terraform:
    executor: docker-terraform
    steps:
      - terraform-apply-changes:
          environment: "production"
  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "staging"
  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

workflows:
  feature:
    jobs:
      - check-code-formatting
      - build-and-test
      - assume-role-staging:
          context: api-assume-role-staging-context
          filters:
            branches:
              ignore: master
      - preview-terraform:
          name: preview-staging-terraform
          environment: "staging"
          requires:
            - assume-role-staging
      - assume-role-production:
          context: api-assume-role-production-context
          filters:
            branches:
              ignore: master
      - preview-terraform:
          name: preview-production-terraform
          environment: "production"
          requires:
            - assume-role-production

  deploy-api-code-stg-and-prod:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - assume-role-staging:
          context: api-assume-role-staging-context
          requires:
            - build-and-test
      - deploy-to-staging:
          context: "Serverless Framework"
          requires:
            - assume-role-staging
      - permit-production-deployment:
          type: approval
          requires:
            - deploy-to-staging
      - assume-role-production:
          context: api-assume-role-production-context
          requires:
            - permit-production-deployment
      - deploy-to-production:
          context: "Serverless Framework"
          requires:
            - assume-role-production

  deploy-staging-and-production-terraform:
    jobs:
      - start-staging-terraform-release:
          type: approval
          filters:
            branches:
              only: master
      - assume-role-staging:
          context: api-assume-role-staging-context
          requires:
            - start-staging-terraform-release
      - preview-terraform:
          name: preview-staging-terraform
          environment: "staging"
          requires:
            - assume-role-staging
      - permit-staging-terraform-release:
          type: approval
          requires:
            - preview-staging-terraform
      - release-staging-terraform:
          requires:
            - permit-staging-terraform-release
      - permit-production-terraform-workflow:
          type: approval
          requires:
            - release-staging-terraform
          filters:
            branches:
              only: master
      - assume-role-production:
          context: api-assume-role-production-context
          requires:
            - permit-production-terraform-workflow
          filters:
            branches:
              only: master
      - preview-terraform:
          name: preview-production-terraform
          environment: "production"
          requires:
            - assume-role-production
      - continue-with-production-terraform-release:
          type: approval
          requires:
            - preview-terraform-production-changes
          filters:
            branches:
              only: master
      - release-production-terraform:
          requires:
            - continue-with-production-terraform-release
          filters:
            branches:
              only: master
