version: 2.1

orbs:
  node: circleci/node@7.2.1
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.1

executors:
  docker-python:
    docker:
      - image: cimg/python:3.14
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:latest"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  master_only: &master_only
    branches:
      only: master
  ignore_master: &ignore_master
    branches:
      ignore: master

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Run formatter check
          command: dotnet format --verify-no-changes --severity warn
  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker compose build addresses-api-test
      - run:
          name: Run tests
          command: |
            docker compose up -d test-elasticsearch
            docker compose run addresses-api-test
  assume-role:
    executor: docker-python
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  execute-terraform:
    executor: docker-terraform
    parameters:
      environment:
        type: enum
        enum: ["staging", "production"]
      action:
        type: enum
        enum: ["preview", "deploy"]
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Terraform Init
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
      - run:
          name: Terraform <<parameters.action>>
          command: |
            cd ./terraform/<<parameters.environment>>/

            if [ "<<parameters.action>>" = "preview" ]; then
              terraform plan
            elif [ "<<parameters.action>>" = "deploy" ]; then
              terraform apply -auto-approve
            fi
  deploy-lambda:
    executor: docker-dotnet
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - node/install
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            sls deploy --stage <<parameters.stage>> --conceal

workflows:
  feature:
    jobs:
      - check-code-formatting:
          filters: *ignore_master
      - build-and-test:
          filters: *ignore_master
      - assume-role:
          name: assume-role-staging
          context: api-assume-role-staging-context
          aws-account: $AWS_ACCOUNT_STAGING
          filters: *ignore_master
      - execute-terraform:
          name: preview-staging-terraform
          environment: "staging"
          action: "preview"
          requires: [assume-role-staging]
      - assume-role:
          name: assume-role-production
          context: api-assume-role-production-context
          aws-account: $AWS_ACCOUNT_PRODUCTION
          filters: *ignore_master
      - execute-terraform:
          name: preview-production-terraform
          environment: "production"
          action: "preview"
          requires: [assume-role-production]

  deploy-api-code-stg-and-prod:
    jobs:
      - build-and-test:
          filters: *master_only
      - assume-role:
          name: assume-role-staging
          context: api-assume-role-staging-context
          aws-account: $AWS_ACCOUNT_STAGING
          requires: [build-and-test]
      - deploy-lambda:
          name: deploy-to-staging
          stage: "staging"
          context: "Serverless Framework"
          requires: [assume-role-staging]
      - permit-production-deployment:
          type: approval
          requires: [deploy-to-staging]
      - assume-role:
          name: assume-role-production
          context: api-assume-role-production-context
          aws-account: $AWS_ACCOUNT_PRODUCTION
          requires: [permit-production-deployment]
      - deploy-lambda:
          name: deploy-to-production
          stage: "production"
          context: "Serverless Framework"
          requires: [assume-role-production]

  deploy-staging-and-production-terraform:
    jobs:
      - start-staging-terraform-release:
          type: approval
          filters: *master_only
      - assume-role:
          name: assume-role-staging
          context: api-assume-role-staging-context
          aws-account: $AWS_ACCOUNT_STAGING
          requires: [start-staging-terraform-release]
      - execute-terraform:
          name: preview-staging-terraform
          environment: "staging"
          action: "preview"
          requires: [assume-role-staging]
      - permit-staging-terraform-release:
          type: approval
          requires: [preview-staging-terraform]
      - execute-terraform:
          name: release-staging-terraform
          environment: "staging"
          action: "deploy"
          requires: [permit-staging-terraform-release]
      - start-production-terraform-release:
          type: approval
          filters: *master_only
      - assume-role:
          name: assume-role-production
          context: api-assume-role-production-context
          aws-account: $AWS_ACCOUNT_PRODUCTION
          requires: [start-production-terraform-release]
      - execute-terraform:
          name: preview-production-terraform
          environment: "production"
          action: "preview"
          requires: [assume-role-production]
      - permit-production-terraform-release:
          type: approval
          requires: [preview-production-terraform]
      - execute-terraform:
          name: release-production-terraform
          environment: "production"
          action: "deploy"
          requires: [permit-production-terraform-release]
