CREATE SCHEMA IF NOT EXISTS dbo;

/****** Object:  Table [dbo].[hackney_address]    Script Date: 04/04/2019 12:32:33 ******/
CREATE TABLE dbo.hackney_address(
	lpi_key varchar(14) NULL,
	lpi_logical_status varchar(18) NULL,
	lpi_start_date int NOT NULL,
	lpi_end_date int NULL,
	lpi_last_update_date int NOT NULL,
	usrn int NOT NULL,
	uprn float NOT NULL,
	parent_uprn float NULL,
	blpu_start_date int NULL,
	blpu_end_date int NULL,
	blpu_state smallint NULL,
	blpu_state_date int NULL,
	blpu_last_update_date int NULL,
	blpu_class varchar(4) NULL,
	usage_description varchar(160) NULL,
	usage_primary varchar(160) NULL,
	property_shell boolean NULL,
	easting numeric(12, 4) NULL,
	northing numeric(12, 4) NULL,
	organisation varchar(100) NULL,
	sao_text varchar(90) NULL,
	unit_number varchar(17) NULL,
	lpi_level varchar(30) NULL,
	pao_text varchar(90) NULL,
	paon_start_num smallint NULL,
	building_number varchar(17) NULL,
	street_description varchar(100) NOT NULL,
	locality varchar(35) NULL,
	ward varchar(100) NULL,
	town varchar(30) NULL,
	county varchar(30) NULL,
	postcode varchar(8) NULL,
	postcode_nospace varchar(8) NULL,
	planning_use_class varchar(50) NULL,
	neverexport boolean NOT NULL,
	longitude float NULL,
	latitude float NULL,
	gazetteer varchar(5) NOT NULL,
	line1 varchar(90) NULL,
	line2 varchar(120) NULL,
	line3 varchar(120) NULL,
	line4 varchar(30) NULL
);

/****** Object:  Table [dbo].[national_address]    Script Date: 04/04/2019 12:32:33 ******/
CREATE TABLE dbo.national_address(
	lpi_key varchar(14) NULL,
	lpi_logical_status varchar(18) NULL,
	lpi_start_date int NOT NULL,
	lpi_end_date int NULL,
    blpu_last_update_date int NULL,
	lpi_last_update_date int NOT NULL,
	usrn int NOT NULL,
	uprn float NOT NULL,
	parent_uprn float NULL,
	blpu_start_date int NOT NULL,
	blpu_end_date int NULL,
	blpu_state smallint NULL,
	blpu_state_date int NULL,
	blpu_class varchar(6) NOT NULL,
	usage_description varchar(1006) NOT NULL,
	usage_primary varchar(250) NOT NULL,
	property_shell boolean NULL,
	easting numeric(12, 4) NULL,
	northing numeric(12, 4) NULL,
	organisation varchar(100) NULL,
	sao_text varchar(90) NULL,
	unit_number varchar(17) NULL,
	lpi_level varchar(30) NULL,
	pao_text varchar(90) NULL,
	paon_start_num smallint NULL,
	building_number varchar(17) NULL,
	street_description varchar(100) NOT NULL,
	locality varchar(100) NULL,
	ward varchar(100) NULL,
	town varchar(100) NULL,
	county varchar(100) NULL,
	postcode varchar(8) NULL,
	postcode_nospace varchar(8) NULL,
	planning_use_class varchar(50) NULL,
	neverexport boolean NOT NULL,
	longitude numeric(12, 9) NULL,
	latitude numeric(12, 9) NULL,
	gazetteer varchar(8) NOT NULL,
	line1 varchar(200) NULL,
	line2 varchar(200) NULL,
	line3 varchar(200) NULL,
	line4 varchar(100) NULL
);

/****** Object:  Table [dbo].[hackney_xref]    Script Date: 04/04/2019 12:32:33 ******/
CREATE TABLE dbo.hackney_xref(
	xref_key varchar(14) NULL,
	uprn float NOT NULL,
	xref_code varchar(6) NULL,
	xref_name varchar(100) NULL,
	xref_value varchar(50) NULL,
	xref_end_date timestamp NULL
);
create view dbo.combined_address as  SELECT * FROM dbo.hackney_address   UNION ALL  SELECT * FROM dbo.national_address;
