// <auto-generated />
using System;
using AddressesAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AddressesAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AddressesContext))]
    [Migration("20260924061930_MakeNationalAddressPropertyChangeDateNullable")]
    partial class MakeNationalAddressPropertyChangeDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AddressesAPI.Infrastructure.Address", b =>
                {
                    b.Property<string>("AddressKey")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("lpi_key");

                    b.Property<int>("AddressChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_last_update_date");

                    b.Property<int>("AddressEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_end_date");

                    b.Property<int>("AddressStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_start_date");

                    b.Property<string>("AddressStatus")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("lpi_logical_status");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("pao_text");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("building_number");

                    b.Property<double>("Easting")
                        .HasColumnType("double precision")
                        .HasColumnName("easting");

                    b.Property<string>("Gazetteer")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gazetteer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line2");

                    b.Property<string>("Line3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line3");

                    b.Property<string>("Line4")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line4");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double>("Northing")
                        .HasColumnType("double precision")
                        .HasColumnName("northing");

                    b.Property<string>("Organisation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organisation");

                    b.Property<bool>("OutOfBoroughAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("neverexport");

                    b.Property<short?>("PaonStartNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("paon_start_num");

                    b.Property<long?>("ParentUPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_uprn");

                    b.Property<string>("PlanningUseClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("planning_use_class");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode");

                    b.Property<string>("PostcodeNoSpace")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode_nospace");

                    b.Property<int>("PropertyChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_last_update_date");

                    b.Property<int>("PropertyEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_end_date");

                    b.Property<bool>("PropertyShell")
                        .HasColumnType("boolean")
                        .HasColumnName("property_shell");

                    b.Property<int>("PropertyStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_start_date");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street_description");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("town");

                    b.Property<long>("UPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("uprn");

                    b.Property<int?>("USRN")
                        .HasColumnType("integer")
                        .HasColumnName("usrn");

                    b.Property<string>("UnitName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("sao_text");

                    b.Property<int?>("UnitNumber")
                        .HasColumnType("integer")
                        .HasColumnName("unit_number");

                    b.Property<string>("UsageCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("blpu_class");

                    b.Property<string>("UsageDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_description");

                    b.Property<string>("UsagePrimary")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_primary");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("AddressKey");

                    b.ToTable((string)null);

                    b.ToView("combined_address", "dbo");
                });

            modelBuilder.Entity("AddressesAPI.Infrastructure.CrossReference", b =>
                {
                    b.Property<string>("CrossRefKey")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("xref_key");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("xref_code");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("xref_end_date");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("xref_name");

                    b.Property<long>("UPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("uprn");

                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("xref_value");

                    b.HasKey("CrossRefKey");

                    b.ToTable("hackney_xref", "dbo");
                });

            modelBuilder.Entity("AddressesAPI.Infrastructure.HackneyAddress", b =>
                {
                    b.Property<string>("AddressKey")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("lpi_key");

                    b.Property<int>("AddressChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_last_update_date");

                    b.Property<int>("AddressEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_end_date");

                    b.Property<int>("AddressStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_start_date");

                    b.Property<string>("AddressStatus")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("lpi_logical_status");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("pao_text");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("building_number");

                    b.Property<double>("Easting")
                        .HasColumnType("double precision")
                        .HasColumnName("easting");

                    b.Property<string>("Gazetteer")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gazetteer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line2");

                    b.Property<string>("Line3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line3");

                    b.Property<string>("Line4")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line4");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool>("NeverExport")
                        .HasColumnType("boolean")
                        .HasColumnName("neverexport");

                    b.Property<double>("Northing")
                        .HasColumnType("double precision")
                        .HasColumnName("northing");

                    b.Property<string>("Organisation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organisation");

                    b.Property<short?>("PaonStartNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("paon_start_num");

                    b.Property<long?>("ParentUPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_uprn");

                    b.Property<string>("PlanningUseClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("planning_use_class");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode");

                    b.Property<string>("PostcodeNoSpace")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode_nospace");

                    b.Property<int>("PropertyChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_last_update_date");

                    b.Property<int>("PropertyEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_end_date");

                    b.Property<bool>("PropertyShell")
                        .HasColumnType("boolean")
                        .HasColumnName("property_shell");

                    b.Property<int>("PropertyStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_start_date");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street_description");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("town");

                    b.Property<long>("UPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("uprn");

                    b.Property<int?>("USRN")
                        .HasColumnType("integer")
                        .HasColumnName("usrn");

                    b.Property<string>("UnitName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("sao_text");

                    b.Property<int?>("UnitNumber")
                        .HasColumnType("integer")
                        .HasColumnName("unit_number");

                    b.Property<string>("UsageCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("blpu_class");

                    b.Property<string>("UsageDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_description");

                    b.Property<string>("UsagePrimary")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_primary");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("AddressKey");

                    b.ToTable("hackney_address", "dbo");
                });

            modelBuilder.Entity("AddressesAPI.Infrastructure.NationalAddress", b =>
                {
                    b.Property<string>("AddressKey")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("lpi_key");

                    b.Property<int>("AddressChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_last_update_date");

                    b.Property<int>("AddressEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_end_date");

                    b.Property<int>("AddressStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("lpi_start_date");

                    b.Property<string>("AddressStatus")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("lpi_logical_status");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("pao_text");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("building_number");

                    b.Property<double>("Easting")
                        .HasColumnType("double precision")
                        .HasColumnName("easting");

                    b.Property<string>("Gazetteer")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("gazetteer");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Line1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line2");

                    b.Property<string>("Line3")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("line3");

                    b.Property<string>("Line4")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line4");

                    b.Property<string>("Locality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool>("NeverExport")
                        .HasColumnType("boolean")
                        .HasColumnName("neverexport");

                    b.Property<double>("Northing")
                        .HasColumnType("double precision")
                        .HasColumnName("northing");

                    b.Property<string>("Organisation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organisation");

                    b.Property<short?>("PaonStartNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("paon_start_num");

                    b.Property<long?>("ParentUPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_uprn");

                    b.Property<string>("PlanningUseClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("planning_use_class");

                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode");

                    b.Property<string>("PostcodeNoSpace")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("postcode_nospace");

                    b.Property<int?>("PropertyChangeDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_last_update_date");

                    b.Property<int>("PropertyEndDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_end_date");

                    b.Property<bool>("PropertyShell")
                        .HasColumnType("boolean")
                        .HasColumnName("property_shell");

                    b.Property<int>("PropertyStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("blpu_start_date");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street_description");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("town");

                    b.Property<long>("UPRN")
                        .HasColumnType("bigint")
                        .HasColumnName("uprn");

                    b.Property<int?>("USRN")
                        .HasColumnType("integer")
                        .HasColumnName("usrn");

                    b.Property<string>("UnitName")
                        .HasMaxLength(90)
                        .HasColumnType("character varying(90)")
                        .HasColumnName("sao_text");

                    b.Property<int?>("UnitNumber")
                        .HasColumnType("integer")
                        .HasColumnName("unit_number");

                    b.Property<string>("UsageCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("blpu_class");

                    b.Property<string>("UsageDescription")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_description");

                    b.Property<string>("UsagePrimary")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("usage_primary");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("AddressKey");

                    b.ToTable("national_address", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
